"""Prometheus metric definitions for the Orchestrator Platform.

This module defines all Prometheus metrics as module-level singletons.
Other modules import and use these metrics directly:

    from orchestrator.observability.metrics import TASK_STATE_TRANSITIONS_TOTAL

    TASK_STATE_TRANSITIONS_TOTAL.labels(
        from_state="created", to_state="queued", agent_type="coder"
    ).inc()

Metrics are exposed at GET /metrics without authentication via the
health routes module using prometheus_client.generate_latest().

Metric categories:
- Task counters (by state, agent_type)
- Queue depth gauges (by agent_type)
- Request latency histograms (by method, path, status_code)
- Worker status gauges (active, idle, dead)
- Error counters (by error_type, component)
- Inference slot utilization (by model)
- Resource budget gauges
- Safe mode gauge
- Timing metrics for classification, state transitions, queue ops, approvals
"""

from __future__ import annotations

from prometheus_client import Counter, Gauge, Histogram

# ---------------------------------------------------------------------------
# Task Counters
# ---------------------------------------------------------------------------

TASK_STATE_TRANSITIONS_TOTAL = Counter(
    "orchestrator_task_state_transitions_total",
    "Total number of task state transitions",
    labelnames=["from_state", "to_state", "agent_type"],
)

TASKS_CREATED_TOTAL = Counter(
    "orchestrator_tasks_created_total",
    "Total number of tasks created",
    labelnames=["agent_type", "priority"],
)

ROOT_TASKS_CREATED_TOTAL = Counter(
    "orchestrator_root_tasks_created_total",
    "Total number of root tasks created",
    labelnames=["entrypoint", "agent_type"],
)

PLANNER_SUBTASKS_CREATED_TOTAL = Counter(
    "orchestrator_planner_subtasks_created_total",
    "Total number of subtasks generated by planner executions",
    labelnames=["assigned_agent", "requires_approval"],
)

PLANNER_INVALID_OUTPUT_TOTAL = Counter(
    "orchestrator_planner_invalid_output_total",
    "Total number of invalid planner outputs",
)

TASKS_COMPLETED_TOTAL = Counter(
    "orchestrator_tasks_completed_total",
    "Total number of tasks reaching terminal states",
    labelnames=["state", "agent_type"],
)

# ---------------------------------------------------------------------------
# Queue Depth Gauges
# ---------------------------------------------------------------------------

QUEUE_DEPTH = Gauge(
    "orchestrator_queue_depth",
    "Current queue depth per agent type",
    labelnames=["agent_type"],
)

QUEUE_DEPTH_TOTAL = Gauge(
    "orchestrator_queue_depth_total",
    "Total queue depth across all agent types",
)

# ---------------------------------------------------------------------------
# Request Latency Histograms
# ---------------------------------------------------------------------------

REQUEST_LATENCY_SECONDS = Histogram(
    "orchestrator_request_latency_seconds",
    "HTTP request latency in seconds",
    labelnames=["method", "path", "status_code"],
    buckets=(0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0),
)

# ---------------------------------------------------------------------------
# Worker Status Gauges
# ---------------------------------------------------------------------------

WORKERS_ACTIVE = Gauge(
    "orchestrator_workers_active",
    "Number of workers currently executing tasks",
)

WORKERS_IDLE = Gauge(
    "orchestrator_workers_idle",
    "Number of workers registered but not executing tasks",
)

WORKERS_DEAD = Gauge(
    "orchestrator_workers_dead",
    "Number of workers detected as dead (missed heartbeats)",
)

# ---------------------------------------------------------------------------
# Error Counters
# ---------------------------------------------------------------------------

ERRORS_TOTAL = Counter(
    "orchestrator_errors_total",
    "Total number of errors by type and component",
    labelnames=["error_type", "component"],
)

# ---------------------------------------------------------------------------
# Inference Slot Utilization
# ---------------------------------------------------------------------------

INFERENCE_SLOTS_AVAILABLE = Gauge(
    "orchestrator_inference_slots_available",
    "Available inference slots per model",
    labelnames=["model"],
)

INFERENCE_SLOTS_TOTAL = Gauge(
    "orchestrator_inference_slots_total",
    "Total inference slots per model",
    labelnames=["model"],
)

INFERENCE_SLOTS_IN_USE = Gauge(
    "orchestrator_inference_slots_in_use",
    "Inference slots currently in use per model",
    labelnames=["model"],
)

# ---------------------------------------------------------------------------
# Resource Budget Gauges
# ---------------------------------------------------------------------------

RESOURCE_TASKS_ACTIVE = Gauge(
    "orchestrator_resource_tasks_active",
    "Number of active tasks per agent type",
    labelnames=["agent_type"],
)

RESOURCE_MAX_CONCURRENT_TASKS = Gauge(
    "orchestrator_resource_max_concurrent_tasks",
    "Configured maximum concurrent tasks",
)

RESOURCE_MEMORY_AVAILABLE_MB = Gauge(
    "orchestrator_resource_memory_available_mb",
    "Available memory in MB as reported by workers",
)

# ---------------------------------------------------------------------------
# Safe Mode Gauge
# ---------------------------------------------------------------------------

SAFE_MODE_ENABLED = Gauge(
    "orchestrator_safe_mode_enabled",
    "Whether safe mode is currently enabled (1=enabled, 0=disabled)",
)

# ---------------------------------------------------------------------------
# Timing Metrics — Classification
# ---------------------------------------------------------------------------

CLASSIFICATION_DURATION_SECONDS = Histogram(
    "orchestrator_classification_duration_seconds",
    "Time taken to classify a task",
    labelnames=["method", "result"],
    buckets=(0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0),
)

# ---------------------------------------------------------------------------
# Timing Metrics — State Transitions
# ---------------------------------------------------------------------------

STATE_TRANSITION_DURATION_SECONDS = Histogram(
    "orchestrator_state_transition_duration_seconds",
    "Time taken to execute a state transition (including DB + side effects)",
    labelnames=["from_state", "to_state"],
    buckets=(0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0),
)

# ---------------------------------------------------------------------------
# Timing Metrics — Queue Operations
# ---------------------------------------------------------------------------

QUEUE_ENQUEUE_DURATION_SECONDS = Histogram(
    "orchestrator_queue_enqueue_duration_seconds",
    "Time taken to enqueue a task",
    labelnames=["agent_type"],
    buckets=(0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25),
)

QUEUE_DEQUEUE_DURATION_SECONDS = Histogram(
    "orchestrator_queue_dequeue_duration_seconds",
    "Time taken to dequeue a task",
    labelnames=["agent_type"],
    buckets=(0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0),
)

# ---------------------------------------------------------------------------
# Timing Metrics — Approval Response Time
# ---------------------------------------------------------------------------

APPROVAL_RESPONSE_TIME_SECONDS = Histogram(
    "orchestrator_approval_response_time_seconds",
    "Time between approval request and resolution",
    labelnames=["action_type", "decision"],
    buckets=(1.0, 5.0, 10.0, 30.0, 60.0, 120.0, 300.0, 600.0),
)

PLANNER_EXECUTION_DURATION_SECONDS = Histogram(
    "orchestrator_planner_execution_duration_seconds",
    "Time taken to produce a planner output",
    buckets=(0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0, 60.0),
)

ROOT_TASK_DURATION_SECONDS = Histogram(
    "orchestrator_root_task_duration_seconds",
    "Wall-clock duration from root task creation to completion",
    labelnames=["final_state"],
    buckets=(1.0, 5.0, 10.0, 30.0, 60.0, 120.0, 300.0, 900.0, 1800.0, 3600.0),
)

CAPABILITY_INVOCATIONS_TOTAL = Counter(
    "orchestrator_capability_invocations_total",
    "Total number of capability invocations",
    labelnames=["capability", "entrypoint", "status"],
)

CAPABILITY_ERRORS_TOTAL = Counter(
    "orchestrator_capability_errors_total",
    "Total number of failed capability invocations",
    labelnames=["capability", "entrypoint"],
)

CAPABILITY_DURATION_SECONDS = Histogram(
    "orchestrator_capability_duration_seconds",
    "Time taken by capability invocations",
    labelnames=["capability", "entrypoint"],
    buckets=(0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0),
)

ARTIFACTS_CREATED_TOTAL = Counter(
    "orchestrator_artifacts_created_total",
    "Total number of persisted artifacts",
    labelnames=["artifact_type", "entrypoint"],
)

# ---------------------------------------------------------------------------
# Scheduler Queue Wait
# ---------------------------------------------------------------------------

SCHEDULER_QUEUE_WAIT_SECONDS = Histogram(
    "orchestrator_scheduler_queue_wait_seconds",
    "Time a task spends waiting in queue before assignment",
    labelnames=["agent_type"],
    buckets=(1.0, 5.0, 10.0, 30.0, 60.0, 120.0, 300.0, 600.0, 1800.0, 3600.0),
)


# ---------------------------------------------------------------------------
# Helper Functions
# ---------------------------------------------------------------------------


def set_safe_mode(enabled: bool) -> None:
    """Update the safe_mode gauge to reflect current status.

    Args:
        enabled: Whether safe mode is currently enabled.
    """
    SAFE_MODE_ENABLED.set(1 if enabled else 0)


def record_task_created(agent_type: str, priority: str) -> None:
    """Record a new task creation.

    Args:
        agent_type: The agent type assigned to the task.
        priority: The task priority level.
    """
    TASKS_CREATED_TOTAL.labels(agent_type=agent_type, priority=priority).inc()


def record_root_task_created(entrypoint: str, agent_type: str) -> None:
    ROOT_TASKS_CREATED_TOTAL.labels(entrypoint=entrypoint, agent_type=agent_type).inc()


def record_planner_subtask_created(assigned_agent: str, requires_approval: bool) -> None:
    PLANNER_SUBTASKS_CREATED_TOTAL.labels(
        assigned_agent=assigned_agent,
        requires_approval=str(requires_approval).lower(),
    ).inc()


def record_planner_invalid_output() -> None:
    PLANNER_INVALID_OUTPUT_TOTAL.inc()


def record_capability_invocation(
    capability: str,
    entrypoint: str,
    status: str,
    duration_seconds: float,
) -> None:
    CAPABILITY_INVOCATIONS_TOTAL.labels(
        capability=capability,
        entrypoint=entrypoint,
        status=status,
    ).inc()
    CAPABILITY_DURATION_SECONDS.labels(
        capability=capability,
        entrypoint=entrypoint,
    ).observe(max(duration_seconds, 0.0))
    if status != "success":
        CAPABILITY_ERRORS_TOTAL.labels(
            capability=capability,
            entrypoint=entrypoint,
        ).inc()


def record_artifact_created(artifact_type: str, entrypoint: str) -> None:
    ARTIFACTS_CREATED_TOTAL.labels(
        artifact_type=artifact_type,
        entrypoint=entrypoint,
    ).inc()


def record_state_transition(
    from_state: str, to_state: str, agent_type: str = "unknown"
) -> None:
    """Record a task state transition.

    Args:
        from_state: The source state.
        to_state: The target state.
        agent_type: The agent type of the task.
    """
    TASK_STATE_TRANSITIONS_TOTAL.labels(
        from_state=from_state, to_state=to_state, agent_type=agent_type
    ).inc()


def record_task_terminal(state: str, agent_type: str = "unknown") -> None:
    """Record a task reaching a terminal state.

    Args:
        state: The terminal state (completed, failed, cancelled).
        agent_type: The agent type of the task.
    """
    TASKS_COMPLETED_TOTAL.labels(state=state, agent_type=agent_type).inc()


def update_queue_depth(agent_type: str, depth: int) -> None:
    """Update the queue depth gauge for an agent type.

    Args:
        agent_type: The agent type queue.
        depth: Current queue depth.
    """
    QUEUE_DEPTH.labels(agent_type=agent_type).set(depth)


def update_queue_depth_total(total: int) -> None:
    """Update the total queue depth gauge.

    Args:
        total: Total queue depth across all agent types.
    """
    QUEUE_DEPTH_TOTAL.set(total)


def update_worker_status(active: int, idle: int, dead: int) -> None:
    """Update worker status gauges.

    Args:
        active: Number of workers currently executing tasks.
        idle: Number of idle workers.
        dead: Number of dead workers.
    """
    WORKERS_ACTIVE.set(active)
    WORKERS_IDLE.set(idle)
    WORKERS_DEAD.set(dead)


def update_inference_slots(
    model: str, available: int, total: int, in_use: int
) -> None:
    """Update inference slot gauges for a model.

    Args:
        model: The model identifier (e.g., "code", "planner", "utility").
        available: Number of available slots.
        total: Total number of slots.
        in_use: Number of slots currently in use.
    """
    INFERENCE_SLOTS_AVAILABLE.labels(model=model).set(available)
    INFERENCE_SLOTS_TOTAL.labels(model=model).set(total)
    INFERENCE_SLOTS_IN_USE.labels(model=model).set(in_use)


def update_resource_tasks_active(agent_type: str, count: int) -> None:
    """Update the active task count for an agent type.

    Args:
        agent_type: The agent type.
        count: Number of active tasks.
    """
    RESOURCE_TASKS_ACTIVE.labels(agent_type=agent_type).set(count)


def record_error(error_type: str, component: str) -> None:
    """Record an error occurrence.

    Args:
        error_type: Classification of the error (e.g., "timeout", "connection", "validation").
        component: The module/component where the error occurred.
    """
    ERRORS_TOTAL.labels(error_type=error_type, component=component).inc()
